matrix:
 include:
  - language: node_js
   node_js:
     - "stable"
   cache:
     directories:
       - "back_end/node_modules"
    before_script:
      - cd back_end
    script:
      - npm test

  - language: android
    dist: trusty
    android:
      components:
        - build-tools-26.0.2
        - android-26
    before_script:
      - cd android/InLine2
    script:
      - ./gradlew build connectedCheck

notifications:
  email:
    - kaikailongwang3@gmail.com

