matrix:
 include:
  -language: node_js
   node_js:
     - "stable"
   cache:
     directories:
       - "back_end/node_modules"
   script:
     - cd back_end
     -npm run test
  
  -language: android
   dist: trusty
   android:
     components:
      - build-tools-26.0.2
      - android-26

