matrix:
 include:
  -language: node_js
   node_js:
     - "stable"
   cache:
     directories:
       - "back_end/node_modules"
   script:
     - cd back_end
     -npm run test
  
  language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-25
          - build-tools-25.0.3
      before_script:
        - cd InLine2/
      script:
        - ./gradlew build connectedCheck

